name: Publica na Itch
# Esse fluxo não roda sozinho, precisa ser chamado a partir de outro
# com os parâmetros específicos do projeto. Por exemplo:
#
# jobs:
#   publica:
#     name: Publica na Itch
#     needs: dependencia-anterior-opcional
#     uses: ./.github/workflows/publica-na-itch.yml
#     with:
#       nome_na_itch: qtftp2teste
#       usuario_na_itch: ntmtst
#       branch: arte
#     secrets:
#       itch_io_key: ${{ secrets.ITCH_IO_KEY }}
#
# Ele assume a seguinte estrutura de pastas no repositório:
#
#   .
#   ├── Projeto/   <-- código fonte do jogo em Godot
#   └── Release/   <-- destino do jogo montado
#       └── Web    <-- destino do jogo versão web
#
# Também assume que o jogo é em Godot 4 usando GDScript e não C#.
# Finalmente, para a publicação funcionar, você precisa ter a chave
# da Itch dentro dos segredos do Github, em ITCH_IO_KEY.

on:
  workflow_call:
    inputs:
      nome_na_itch:
        type: string
        required: true
      usuario_na_itch:
        type: string
        required: true
      branch:
        type: string
        required: true
    secrets:
      itch_io_key:
        required: true

env:
  GODOT_VERSAO: '4.4'

jobs:
  exporta-pra-itch:
    name: Exporta pra Itch
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.4  # não aceita interpolação de ${{ GODOT_VERSAO }}
    steps:
      - name: Obtendo repositório
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1
      - name: Configurando
        run: |
          apt-get update && apt-get install -y curl unzip
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv -v /root/.local/share/godot/export_templates/${GODOT_VERSAO}.stable ~/.local/share/godot/export_templates/${GODOT_VERSAO}.stable
      - name: Montando para Web
        working-directory: ./Projeto
        run: |
          rm -rf ${GITHUB_WORKSPACE}/Release/Web/
          mkdir -p ${GITHUB_WORKSPACE}/Release/Web
          godot --headless --export-release Web ${GITHUB_WORKSPACE}/Release/Web/index.html
          ls -lah ${GITHUB_WORKSPACE}/Release/Web
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          echo "Commit = $(git rev-parse HEAD)"
          echo "Pasta = $GITHUB_WORKSPACE/Release/Web"
      - name: Instalando Butler
        run: |
          curl -L -o butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          mv butler /usr/local/bin/
          butler -V  # Verifica a instalação
      - name: Publicando na Itch.io
        run: |
          export BUTLER_API_KEY=${{ secrets.itch_io_key }}
          PACKAGE_PATH="${GITHUB_WORKSPACE}/Release/Web"
          TARGET="${{ inputs.usuario_na_itch }}/${{ inputs.nome_na_itch }}:web"
          echo "Publicando $PACKAGE_PATH para $TARGET"
          git checkout $PACKAGE_PATH/server.py
          butler push "$PACKAGE_PATH" "$TARGET"
          butler status "$TARGET"
